feat: Add `Mutex`
rustyscreeps/screeps-async pull request #4
Opened 2024-03-14 02:13 UTC by scottbot95

Implement async mutex

2024-03-14 02:53 UTC, khoover commented on screeps-async/src/sync/mutex.rs
> +        MutexLockFuture::new(self).await
This is an anti-pattern; if you have a custom future type, make this a sync function and return that custom type.

2024-03-14 02:58 UTC, khoover commented on screeps-async/src/sync/mutex.rs
> +    wakers: UnsafeCell<VecDeque<Rc<UnsafeCell<Waker>>>>,
Why not just `UnsafeCell<Exclusive<VecDequeue<Waker>>>`? Now the Mutex is send + sync and you avoided the Rc/RefCell overhead.

2024-03-14 02:58 UTC, khoover commented on screeps-async/src/sync/mutex.rs
> +}
Have you considered adding an `async fn unlock_fair(self)` that forces a yield back to the executor after unlocking?

2024-03-14 03:01 UTC, khoover commented on screeps-async/src/sync/mutex.rs
> +    wakers: UnsafeCell<VecDeque<Rc<UnsafeCell<Waker>>>>,
Disregard  forgot the blanket !Sync for UnsafeCell. You'd need to manually add Send + Sync impls for the Mutex.

2024-03-14 04:26 UTC, scottbot95 commented on screeps-async/src/sync/mutex.rs
> +        MutexLockFuture::new(self).await
Ah interesting. I'd seen some example doing basically this which makes some sense to me as the return type is more obvious in this case. However I can see how the extra layer of wrapping would be considered an anti-pattern.

2024-03-14 04:37 UTC, scottbot95 commented on screeps-async/src/sync/mutex.rs
> +    wakers: UnsafeCell<VecDeque<Rc<UnsafeCell<Waker>>>>,
I was not aware of `Exclusive`. Looks like that's a nightly only feature though and I don't want to require that of users.

Also the inner Rc<UnsafeCell<Waker>> is used so I can share a mutable reference to the waker between here (where it will be called from) and the Future implementation (so that it can be updated via `Waker::clone_from`).

Good catch on the Send + Sync, I will add those.

2024-03-14 04:49 UTC, khoover commented on screeps-async/src/sync/mutex.rs
> +        MutexLockFuture::new(self).await
It's the same as Iterator-implementing types, if you can return the exact struct over an `impl Iterator` it probably makes more sense to return the exact struct.

2024-03-14 05:06 UTC, scottbot95 commented on screeps-async/src/sync/mutex.rs
> +}
Hmmm I had not thought about that. What that be a function on the guard then? Or perhaps an associated function on Mutex that consumes the guard? I'm envisioning something like this (probably would make regular `unlock` public too and rework it to also consume the guard)

```rs
impl<T> Mutex<T> {
    pub async fn unlock_fair(guard: MutexGuard<'_, T>) {
        drop(guard);
        crate::yield_now().await;
    }
}


```

2024-03-14 05:15 UTC, khoover commented on screeps-async/src/sync/mutex.rs
> +    wakers: UnsafeCell<VecDeque<Rc<UnsafeCell<Waker>>>>,
Is it still nightly-only? Bother, you'd think such a simple thing would have stabilized already given the benefits.

Also, I just remembered the other problem with only popping a single `Waker`; what if the Future that added the Waker has since been dropped/forgotten, so now it never takes the lock or wakes any of the other pending wakers? If you drain the queue each time, then I think the updating point becomes moot.

2024-03-14 05:44 UTC, khoover commented on screeps-async/src/sync/mutex.rs
> +}
I'd say make it a method on the guard, making it an associated function of the Mutex feels odd to me.

2024-03-14 06:03 UTC, khoover commented on screeps-async/src/sync/mutex.rs
> +        Some(MutexGuard::new(self))
Fun fact: the way AtomicBool works, you can rewrite this as
```rust
self.state
    .store(true, Ordering::Acquire)
    .then(|| MutexGuard::new(self))
```

2024-03-14 06:03 UTC, khoover commented on screeps-async/src/sync/mutex.rs
> +        self.state.swap(false, Ordering::Release);
Ditto here, no need for `swap`, just `store`.

2024-03-15 02:17 UTC, scottbot95 commented on screeps-async/src/sync/mutex.rs
> +        Some(MutexGuard::new(self))
Oh wow that's neat!

2024-03-15 02:18 UTC, scottbot95 commented on screeps-async/src/sync/mutex.rs
> +}
Sure that seems reasonable. I just noticed that `std::sync::Mutex` has an associated `unlock` that consumes the guard.

2024-03-15 06:30 UTC, khoover commented on screeps-async/src/sync/mutex.rs
> +        *wakers = Vec::new();
How about replacing these four lines with `wakers.drain().for_each(Waker::wake);`?

2024-03-15 17:14 UTC, scottbot95 commented on screeps-async/src/sync/mutex.rs
> +        *wakers = Vec::new();
Ah neat. I was unaware of drain. I like that since presumably it will not effect the Vec's capacity so requeueing all the Wakers that are still blocked won't cause churn while growing the new Vec.

2024-03-15 21:35 UTC, khoover requested changes

2024-03-15 21:35 UTC, khoover commented on screeps-async/src/sync/mutex.rs
> +    wakers: UnsafeCell<Vec<Waker>>,
So the way you use `wakers` is actually entirely thread unsafe, e.g. what if one thread is unlocking but another is about to push a waker onto the queue? In light of that, why not skip the `AtomicBool` as well (since this struct is definitely `!Sync`) and instead use a regular one?

2024-03-15 21:57 UTC, scottbot95 commented on screeps-async/src/sync/mutex.rs
> +    wakers: UnsafeCell<Vec<Waker>>,
I am aware that it is thread unsafe, but I figured it doesn't matter since there is only one thread in screeps anyway though, right?

As far as `AtomicBool` vs `Cell<bool>`, I suppose I could use a Cell since we never need to read without writing. I don't see any reason to choose one over the other though (presumably the generated bytecode will be almost identical for both)

2024-03-16 02:52 UTC, khoover commented on screeps-async/src/sync/mutex.rs
> +    wakers: UnsafeCell<Vec<Waker>>,
Agreed for a single-threaded context, it being sync or not doesn't matter.

As for AtomicBool vs. Cell<bool>, in the WASM context there's no difference, but there's also no real reason to use atomic values if the mutex won't be shared between threads. Plus it would then be usable in other single-threaded contexts where atomic bools do have an overhead versus plain booleans.

2024-03-16 04:03 UTC, scottbot95 commented on screeps-async/src/sync/mutex.rs
> +    wakers: UnsafeCell<Vec<Waker>>,
That's fair. I might change it to Cell then. Although I think while it's generally a good thing to not couple the runtime too tightly to screeps/WASM, ultimately that is the only environment I plan to officially support so I'm not *that* adverse to making decisions off restrictions of that environment.

Also, I plan to implement a `RwLock` at some point as well. Idealistically I'd like them to use very similar implementations and I don't think Cell will work for RwLock since we would need to actually use the previous state to compute the next state. It's not that big a deal if they differ though. It would be nice if I could just use [Cell::update](https://doc.rust-lang.org/std/cell/struct.Cell.html#method.update) but that's also nightly for some reason so I'd like to avoid using it (things seem to stay in nightly forever...). I suppose I could always just `Cell::replace` with some junk value and replace a second time after updating the original which probably isn't really much slower at all compared to however `update` would work.

2024-03-16 04:24 UTC, khoover commented on screeps-async/src/sync/mutex.rs
> +    wakers: UnsafeCell<Vec<Waker>>,
For RwLock, I think you could honestly just use a RefCell plus the Waker queue internally, have the future do `try_borrow(_mut)` to attempt to "lock", and get basically all the performance you'd want.

2024-03-16 05:25 UTC, scottbot95 commented on screeps-async/src/sync/mutex.rs
> +    wakers: UnsafeCell<Vec<Waker>>,
Hmm that's a really good point actually

2024-03-18 04:35 UTC, merged